// Explicit Acceptance Testcase: PROMO-CONTENT-GEN
// Maps to intent element: promo-content-generation (Hexo Markdown-to-HTML Generation)
// Maps to intent testcase: ExplicitAcceptanceTestcase-PROMO-CONTENT-GEN
// Frozen during Coding/Repair. Do not modify.

'use strict';

const assert = require('assert');
const { createPromoDeploymentHarness } = require('../../harness/promoDeploymentHarness');

/**
 * PROMO-CONTENT-GEN: Verifies hexo generate converts Markdown source files to static HTML
 * in public/ directory without front-matter parse errors.
 *
 * Control point: Place Markdown source files with valid Hexo front-matter in source/ directory
 * and run hexo generate.
 * Observation point: hexo g exits 0 without parse errors, public/ contains index.html
 * and linked assets with content from the source Markdown files.
 */
async function run() {
  const harness = createPromoDeploymentHarness();
  const results = {};

  // ─── GIVEN SSH access and an initialized Hexo site ───
  const scaffold = harness.observeSiteScaffold();
  results.siteExists = scaffold.exists;
  console.log(`[PROMO-CONTENT-GEN] Site directory exists: ${scaffold.exists}`);

  if (!scaffold.exists) {
    results.failureReason = 'PROMO_CONTENT_GEN_SITE_NOT_INITIALIZED';
    results.failureDetail = 'Hexo site directory not found. Run promo-hexo-ssg installation first.';
    return results;
  }

  // ─── GIVEN a sample Markdown file with valid Hexo front-matter ───
  const sampleTitle = 'Hello ARGO Test Post';
  const sampleContent = `---
title: ${sampleTitle}
date: 2026-08-07
tags:
  - test
  - argo
categories:
  - tech
description: A test post for Hexo content generation verification.
---
## Welcome to ARGO

This is a test post generated by the ARGO promo website deployment pipeline.

Hexo converts this Markdown to static HTML via \`hexo generate\`.

### Verification Points

1. Front-matter is valid YAML between \`---\` delimiters
2. hexo g exits with code 0
3. public/ directory contains index.html
`;

  const samplePath = harness.placeSampleMarkdown(sampleTitle, sampleContent);
  results.samplePath = samplePath;
  console.log(`[PROMO-CONTENT-GEN] Sample Markdown placed at: ${samplePath}`);

  // ─── WHEN we run hexo generate ───
  // THEN it exits 0 and public/ contains generated HTML
  const genResult = harness.observeHexoGenerate();
  results.generate = {
    exitCode: genResult.exitCode,
    hasPublicDir: genResult.hasPublicDir,
    hasIndexHtml: genResult.hasIndexHtml,
  };
  console.log(`[PROMO-CONTENT-GEN] hexo g exit code: ${genResult.exitCode}`);
  console.log(`[PROMO-CONTENT-GEN] public/ exists: ${genResult.hasPublicDir}`);
  console.log(`[PROMO-CONTENT-GEN] public/index.html exists: ${genResult.hasIndexHtml}`);
  console.log(`[PROMO-CONTENT-GEN] Output (last 500 chars): ${(genResult.output || '').slice(-500)}`);

  // ─── THEN verify no front-matter parse errors ───
  const hasFmErrors = harness.observeFrontMatterParseErrors(genResult.output);
  results.hasFrontMatterErrors = hasFmErrors;
  console.log(`[PROMO-CONTENT-GEN] Front-matter parse errors: ${hasFmErrors}`);

  // ─── THEN verify successful generation ───
  const success = harness.observeSuccessfulGeneration(genResult);
  results.generationSuccessful = success;
  console.log(`[PROMO-CONTENT-GEN] Generation successful: ${success}`);

  // ─── THEN check if sample content appears in generated output ───
  if (genResult.hasIndexHtml) {
    const contentCheck = harness.sshExec(
      `grep -c "Hello ARGO Test Post" "${harness.getConfig().siteDir}/public/index.html" 2>/dev/null || echo "0"`
    );
    const matchCount = parseInt(contentCheck.stdout.trim(), 10) || 0;
    results.sampleContentInOutput = matchCount > 0;
    console.log(`[PROMO-CONTENT-GEN] Sample content found in output: ${matchCount > 0} (${matchCount} matches)`);
  } else {
    results.sampleContentInOutput = false;
  }

  // ─── Classify overall result ───
  const allPassed = genResult.exitCode === 0 &&
    genResult.hasPublicDir &&
    genResult.hasIndexHtml &&
    !hasFmErrors &&
    success;

  results.allPassed = allPassed;

  if (!allPassed) {
    const missing = [];
    if (genResult.exitCode !== 0) missing.push(`hexo g exit code ${genResult.exitCode} (expected 0)`);
    if (!genResult.hasPublicDir) missing.push('public/ directory not created');
    if (!genResult.hasIndexHtml) missing.push('public/index.html not generated');
    if (hasFmErrors) missing.push('Front-matter parse errors detected');
    if (!success) missing.push('Generation did not report success');
    results.failureReason = 'PROMO_CONTENT_GEN_NOT_READY';
    results.failureDetail = missing.join('; ');
    if (genResult.stderr) {
      results.stderr = genResult.stderr.slice(-1000);
    }
  }

  return results;
}

// ─── Self-executing entrypoint ──────────────────────────────────────
if (require.main === module) {
  run().then((results) => {
    console.log('\n[PROMO-CONTENT-GEN] Results:', JSON.stringify(results, null, 2));
    if (results.allPassed) {
      console.log('[PROMO-CONTENT-GEN] PASS: Content generation verified.');
      process.exit(0);
    } else {
      console.log(`[PROMO-CONTENT-GEN] EXPECTED FAILURE: ${results.failureReason}`);
      console.log(`[PROMO-CONTENT-GEN] Detail: ${results.failureDetail}`);
      process.exit(1);
    }
  }).catch((err) => {
    console.error('[PROMO-CONTENT-GEN] UNEXPECTED ERROR:', err.message);
    process.exit(2);
  });
}

module.exports = { run };
